clc; close all; clear;

trainData = imageDatastore('train', 'IncludeSubfolders', true, 'LabelSource', 'foldernames');
valData   = imageDatastore('validation', 'IncludeSubfolders', true, 'LabelSource', 'foldernames');

labelCounts = countEachLabel(trainData);
totalSamples = sum(labelCounts.Count);
numClasses = height(labelCounts);
classWeights = totalSamples ./ (numClasses * labelCounts.Count);

net = resnet18;
inputSize = net.Layers(1).InputSize;

augmenter = imageDataAugmenter( ...
    'RandXReflection', true, ...
    'RandRotation', [-15 15], ...
    'RandScale', [0.8 1.2], ...
    'RandXTranslation', [-10 10], ...
    'RandYTranslation', [-10 10]);

augTrain = augmentedImageDatastore(inputSize, trainData, 'DataAugmentation', augmenter);
augVal   = augmentedImageDatastore(inputSize, valData);

lgraph = layerGraph(net);

newFc = fullyConnectedLayer(numClasses, 'Name', 'new_fc', ...
    'WeightLearnRateFactor', 10, 'BiasLearnRateFactor', 10);
newClass = classificationLayer('Name', 'new_classoutput', ...
    'Classes', labelCounts.Label, 'ClassWeights', classWeights);

lgraph = replaceLayer(lgraph, 'fc1000', newFc);
lgraph = replaceLayer(lgraph, 'ClassificationLayer_predictions', newClass);

options = trainingOptions('adam', ...
    'MaxEpochs', 10, ...
    'MiniBatchSize', 16, ...
    'InitialLearnRate', 1e-4, ...
    'ValidationData', augVal, ...
    'ValidationFrequency', 10, ...
    'Shuffle', 'every-epoch', ...
    'Plots', 'training-progress', ...
    'Verbose', true);

trainedNet = trainNetwork(augTrain, lgraph, options);

save('jaundice_resnet_model.mat', 'trainedNet');

evaluate_model(trainedNet, augVal, valData.Labels);
